import supabase from './db-client.js';
import { cors, getAdminAccess, rateLimit, requireAdmin, requireUser, getUser } from './_utils.js';

async function enrichComments(rows=[]){
 const ids=[...new Set(rows.map(row=>row.user_id).filter(Boolean))];if(!ids.length)return rows;
 const[{data:profiles,error},{data:preferences,error:preferenceError}]=await Promise.all([supabase.from('profiles').select('id,email,display_name,role').in('id',ids),supabase.from('admin_preferences').select('id,comment_color').in('id',ids)]);
 if(error||preferenceError)throw error||preferenceError;
 const profileMap=new Map((profiles||[]).map(profile=>[profile.id,profile])),colorMap=new Map((preferences||[]).map(pref=>[pref.id,pref.comment_color]));
 return rows.map(row=>{const profile=profileMap.get(row.user_id),isAdmin=profile?.role==='admin'||profile?.role==='owner';return{...row,display_name:profile?.display_name||row.display_name,is_admin:isAdmin,comment_color:isAdmin?colorMap.get(row.user_id)||'#eab308':null}});
}

export default async function handler(req,res){if(cors(req,res))return;if(!rateLimit(req,res,40))return;try{
 if(req.method==='GET'){let q=supabase.from('comments').select('*').order('created_at',{ascending:false});if(req.query?.all==='true'){if(!await requireAdmin(req,res,'comments'))return}else{q=q.eq('status','approved');if(req.query?.manhwa_id)q=q.eq('manhwa_id',req.query.manhwa_id)}const{data,error}=await q;if(error)throw error;return res.status(200).json(await enrichComments(data||[]))}
 if(req.method==='POST'){const user=await requireUser(req,res);if(!user)return;const body=String(req.body?.body||'').trim(),manhwaId=Number(req.body?.manhwa_id);if(body.length<3||body.length>700)return res.status(400).json({error:'دیدگاه باید بین ۳ تا ۷۰۰ کاراکتر باشد.'});const{count,error:countError}=await supabase.from('comments').select('*',{count:'exact',head:true}).eq('manhwa_id',manhwaId).eq('user_id',user.id);if(countError)throw countError;if((count||0)>=5)return res.status(400).json({error:'هر کاربر برای هر مانهوا حداکثر ۵ کامنت می‌تواند ثبت کند.'});const{data,error}=await supabase.from('comments').insert({manhwa_id:manhwaId,user_id:user.id,display_name:user.user_metadata?.display_name||user.email?.split('@')[0]||'کاربر',body,status:'approved'}).select().single();if(error)throw error;return res.status(201).json(data)}
 if(req.method==='PUT'){const user=await getUser(req);if(!user)return res.status(401).json({error:'وارد حساب شوید.'});const id=Number(req.body?.id),access=await getAdminAccess(user);if(typeof req.body?.body==='string'){const body=req.body.body.trim();if(body.length<3||body.length>700)return res.status(400).json({error:'دیدگاه باید بین ۳ تا ۷۰۰ کاراکتر باشد.'});const{data:comment,error:findError}=await supabase.from('comments').select('user_id').eq('id',id).maybeSingle();if(findError)throw findError;if(!comment)return res.status(404).json({error:'کامنت پیدا نشد.'});if(comment.user_id!==user.id&&!access.permissions.includes('comments'))return res.status(403).json({error:'فقط نویسنده کامنت می‌تواند آن را ویرایش کند.'});const{data,error}=await supabase.from('comments').update({body}).eq('id',id).select().single();if(error)throw error;return res.status(200).json(data)}if(!await requireAdmin(req,res,'comments'))return;const{data,error}=await supabase.from('comments').update({status:req.body?.status}).eq('id',id).select().single();if(error)throw error;return res.status(200).json(data)}
 if(req.method==='DELETE'){const user=await getUser(req);if(!user)return res.status(401).json({error:'وارد حساب شوید.'});const access=await getAdminAccess(user);let q=supabase.from('comments').delete().eq('id',req.body?.id);if(!access.permissions.includes('comments'))q=q.eq('user_id',user.id);const{error}=await q;if(error)throw error;return res.status(200).json({ok:true})}
 return res.status(405).json({error:'Method not allowed'});
}catch(err){console.error('comments API:',err);return res.status(500).json({error:err.message})}}
